
x-airflow-common:
  &airflow-common
  build:
    context: ./image-airflow
    dockerfile: Dockerfile
  env_file:
    - env/airflow.env
  volumes:
    - ./config:/opt/airflow/config
    - ./dags:/opt/airflow/dags
    - ./data:/opt/airflow/data
    - ./logs:/opt/airflow/logs
    - ./pipelines:/opt/airflow/pipelines
    - ./jobs:/opt/airflow/jobs
    - ./utils:/opt/airflow/utils
    - ./image-airflow/requirements.txt:/opt/airflow/requirements.txt
    - ./init/init-airflow.sh:/opt/airflow/init-airflow.sh
  depends_on:
    - postgres
  networks:
    - airflow_net

x-spark-common:
  &spark-common
  build:
    context: ./image-spark
    dockerfile: Dockerfile
  volumes:
    - ./jobs:/opt/bitnami/spark/jobs
  networks:
    - airflow_net

services:

  postgres:
    image: postgres:12
    container_name: postgres
    env_file:
      - env/postgres.env
    networks:
      - airflow_net

  airflow-init:
    <<: *airflow-common
    container_name: airflow-init
    command: ["bash", "/opt/airflow/init-airflow.sh"] 
    restart: "no"

  airflow-webserver:
    <<: *airflow-common
    container_name: airflow-webserver
    command: webserver
    ports:
      - "8080:8080"
    depends_on:
      airflow-init :
        condition: service_completed_successfully
        restart: true

  airflow-scheduler:
    <<: *airflow-common
    container_name: airflow-scheduler
    command: scheduler
    depends_on:
      airflow-init :
        condition: service_completed_successfully
        restart: true

  mongodb:
    image: mongo:5.0
    container_name: mongodb
    env_file:
      - env/mongo.env
    ports:
      - 27017:27017
    networks:
      - airflow_net
    volumes:
      - ./init/init-mongo.sh:/docker-entrypoint-initdb.d/init-mongo.sh
  
  spark-master:
    <<: *spark-common
    container_name : spark-master
    command: bin/spark-class org.apache.spark.deploy.master.Master
    ports:
      - "9090:8080"
      - "7077:7077"

  spark-worker-1:
    <<: *spark-common
    container_name : spark-worker-1
    command: bin/spark-class org.apache.spark.deploy.worker.Worker spark://spark-master:7077
    depends_on:
      - spark-master
    env_file:
      - env/spark-worker.env

  spark-worker-2:
    <<: *spark-common
    container_name : spark-worker-2
    command: bin/spark-class org.apache.spark.deploy.worker.Worker spark://spark-master:7077
    depends_on:
      - spark-master
    env_file:
      - env/spark-worker.env
  
  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    ports:
      - "3000:3000"
    volumes:
      - ./grafana:/var/lib/grafana
    env_file:
      - env/grafana.env
    networks:
      - airflow_net

networks:
  airflow_net:
    driver: bridge
