FROM apache/airflow:2.8.1

COPY requirements.txt /opt/airflow/

USER root
RUN apt-get update && apt-get install -y gcc python3-dev openjdk-17-jdk && apt-get clean

ENV JAVA_HOME /usr/lib/jvm/java-17-openjdk-amd64

USER airflow
RUN pip install --no-cache-dir -r /opt/airflow/requirements.txt
